### ISSUE TITLE
Double-tap Drag Gesture zooms in wrong direction

### ISSUE THREAD

**Issue by and01** [Esri/arcgis-maps-sdk-swift#21]
Not sure if this is a bug, but the zoom direction is different than in both the old iOS 100.X version as well as the current Android version.

**Comment by dfeinzimer** [comment]
Hi @and01, that's a good question. This gesture is designed to match that of Apple Maps to maintain consistency with iOS conventions. With that said, this is expected behavior and not a bug.

I'll close this for now, but if you have further concerns, please reopen with a comment or post in our [Esri Community forum](https://community.esri.com/t5/swift-maps-sdk-questions/bd-p/swift-maps-sdk-questions).
