### ISSUE TITLE
SceneView not showing some Polygons

### ISSUE THREAD

**Issue by saugs** [Esri/arcgis-maps-sdk-swift#26]
Hi,

I'm trying to draw a latitude band on a `SceneView`, but **nothing shows up**. Do you know if there's a trick ?
It works well on a Javascript `SceneView` and on 2D `MapView` (Swift & Javascript).

Can easily reproduce with this code:
```
let geometry = try! Polygon.fromJSON("""
{
  "spatialReference": {"wkid": 4326},
  "rings": [[
      [-180, -12],
      [-180, 12],
      [180, 12],
      [180, -12],
      [-180,-12]
  ]]
}
""")
let graphic = Graphic(geometry: geometry, symbol: SimpleFillSymbol(
    style: .solid,
    color: .systemRed.withAlphaComponent(0.3),
    outline: SimpleLineSymbol(
        style: .solid,
        color: .systemRed,
        width: 3
    )
))

let overlay = GraphicsOverlay()
overlay.addGraphic(graphic)

SceneView(scene: scene, graphicsOverlays: [overlay])
```

This is the **result expected** (screenshot from web Javascript `SceneView`):

<img width="599" alt="Screenshot 2024-12-31 at 20 01 06" src="https://github.com/user-attachments/assets/e93a912d-c83b-4e8f-b3d1-9de38652670b" />

**Comment by yo1995** [comment]
Thanks for the question. I'll reach out to our geometry team to see why it works differently in  the 3D scene view in Maps SDK.

**Comment by saugs** [comment]
Thanks !

By the way, setting the `overlay.renderingMode = .static` fixed this 🤷🏻‍♂️ (cf. #27)

**Comment by yo1995** [comment]
> By the way, setting the `overlay.renderingMode = .static` fixed this 🤷🏻‍♂️ (cf. #27)

Thanks for letting me know. After consulting with our geometry rendering folks, they told me that another way is to densify the geometry like this

`let densifiedGeometry = GeometryEngine.geodeticDensify(geometry, maxSegmentLength: 1000, lengthUnit: .meters, curveType: .shapePreserving)`

so that the rendering pipeline knows where the geometry would be across a large (geodesic) area. I think this problem comes down to how is a big polygon interpreted in 3D with limited vertices. Anyway, glad that it works for you.
