### ISSUE TITLE
Switch of basemaps doesn't work properly when using multiple webmaps

### ISSUE THREAD

**Issue by mmoosbac94** [Esri/arcgis-maps-sdk-swift#7]
With version 200.1 we currently have the issue that the switch of basemaps (also when using basemap-gallery) doesn't work when using multiple webmaps. So we have a viewmodel where we create Map using Map(item: ...). The basemaps are working correctly. When we then switch to another webmap also using Map(item: ...) and so override map in viewModel the switch of basemaps doesn't work properly anymore (so one basemap can be selected, the other cannot). Same issue with the Basemap-gallery (here even both basemaps cannot be selected).

e.g. 
we first fetch default webmap with "item: PortalItem(portal: portal, id: PortalItem.ID("...")!) and after that we load portalItems/webmaps from portal manually with "findItems" and set selected map also in viewmodel.

It's working when we first load all portalItems/webmaps with "findItems" and then choose a portalItem with specific ID.

**Comment by yo1995** [comment]
Thanks for reaching out. Since this is more of a UI/View model issue, would you mind moving this issue to [toolkit repo](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit) or asking on [Esri Community](https://community.esri.com/t5/swift-maps-sdk-questions/bd-p/swift-maps-sdk-questions)?

Also, please clarify 

> doesn't work properly anymore (so one basemap can be selected, the other cannot)

- It seems you are using webmaps from ArcGIS Online given the `Map(item:)` initializer. Are you trying to switch between maps (i.e., [`Map`](https://developers.arcgis.com/swift/api-reference/documentation/arcgis/map) instances), or basemaps ([`Basemap`](https://developers.arcgis.com/swift/api-reference/documentation/arcgis/basemap))?
- Can you further explain "cannot be selected"? i.e., is it an UI issue or a data issue?
- Do you see any error message logged in the console?
- It would be great if you can provide a repro code snippet using the `BasemapGallery` that shows the problem.

Thank you

**Comment by mmoosbac94** [comment]
Thank you for the quick response. We decided to ask here because we aren't sure if it is an sdk issue related to different map initializations. So everything is working fine when using one webmap, but if we initialize another one, its not working properly anymore.

- We are trying to switch basemaps on different webmaps. So switching webmaps is working fine, but the basemaps on the displayed webmap cannot be switched after choosing another webmap (so creating a new map instance with fetched portalItems from ArcGIS Online).
- "Cannot be selected" in this context means to display specific basemap on webmap. We know that the basemaps exist but it's not gonna be updated on webmap.
- There are not error messages related to this issue.

**Comment by rolson** [comment]
cc @mhdostal

**Comment by mmoosbac94** [comment]
Oh yes! Very nice. It's working now if we set basemap to nil prior creating a new map with same basemap. But it only seems to work when we use a custom solution for displaying the selection of basemaps. So when we use the BasemapGallery from ArcGIS Toolkit for a second map it is not working. Maybe the BasemapGallery is only meant to cover one map with basemaps.

Thank you very much for your quick help and reply!

**Comment by mhdostal** [comment]
@mmoosbac94 I just merged a [PR](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/329) into the Toolkit's `v.next` branch which should fix your issue, without changes on your side (when using the `BasemapGallery`). This fix was to clone the basemap prior to setting it on the map. This would only apply when the `BasemapGallery` was initialized with an array of basemap items. When passing in a `Portal`, the basemap list is refreshed when the gallery is displayed, so there is not the "Object already owned" error in that case.

You could employ the same solution when using your custom method for selecting basemaps.  Just call `.clone()` on your basemap, prior to setting it on the existing map.

Hope that helps.
